/**
 * Dietary Guardrail Module
 * Layer 3 Post-Generation Deterministic Safety Filter.
 * 
 * Inspects LLM output against user's personal avoid foods list.
 * Uses shared normalization from fuzzyMatch.js to handle Turkish suffixes (somon -> somonlu/somondan).
 */

const { normalizeString } = require("../tools/utils/fuzzyMatch");

/**
 * Validates assistant response text against user's avoid foods.
 * 
 * @param {string} assistantText - Raw response text generated by LLM
 * @param {Array<string>} unsafeFoods - List of unsafe/avoid food names for the user
 * @returns {{ isSafe: boolean, blockedFoods: Array<string> }} Validation result
 */
function validateDietaryOutput(assistantText, unsafeFoods = []) {
    if (!assistantText || typeof assistantText !== "string" || !Array.isArray(unsafeFoods) || unsafeFoods.length === 0) {
        return { isSafe: true, blockedFoods: [] };
    }

    const normalizedText = normalizeString(assistantText);
    const wordsInText = normalizedText.split(/\s+/);
    const detectedBreaches = new Set();

    for (const rawFood of unsafeFoods) {
        if (!rawFood || typeof rawFood !== "string") continue;
        const normalizedFood = normalizeString(rawFood);
        if (!normalizedFood || normalizedFood.length < 2) continue;

        // 1. Çok kelimeli gıdalar (örn. "balik corbasi", "kirmizi et") için metin içinde substring kontrolü
        if (normalizedFood.includes(" ")) {
            if (normalizedText.includes(normalizedFood)) {
                detectedBreaches.add(rawFood);
            }
            continue;
        }

        // 2. Tek kelimeli gıdalar için Türkçe ekleri (somon -> somonlu, somondan, somonun)
        // kelime başlangıcı (startsWith) ve tam kelime eşleşmesiyle yakalama
        for (const word of wordsInText) {
            if (word.startsWith(normalizedFood)) {
                // Aşırı kısa köklerin yanlışlıkla uzun alakasız kelimelerle eşleşmesini önleme (örn. "et" -> "etkili")
                if (normalizedFood.length <= 2 && word !== normalizedFood) {
                    continue;
                }
                detectedBreaches.add(rawFood);
                break;
            }
        }
    }

    const blockedList = Array.from(detectedBreaches);
    return {
        isSafe: blockedList.length === 0,
        blockedFoods: blockedList
    };
}

/**
 * Generates an empathetic and safe generic fallback response when an unsafe food is caught.
 * 
 * @param {Array<string>} blockedFoods - Unsafe foods that triggered the guardrail
 * @returns {string} Safe fallback message
 */
function createSafetyFallbackResponse(blockedFoods = []) {
    const foodListText = blockedFoods.length > 0
        ? ` (${blockedFoods.join(", ")})`
        : "";

    return `Güvenlik Uyarısı: Önerim kişisel kaçındığınız gıdalar listenizde yer alan bir içerik${foodListText} barındırabileceğinden dolayı sağlığınızı korumak adına durdurulmuştur. Güvenli beslenme yolculuğunuz için lütfen listenizdeki tolere edebildiğiniz alternatif gıdaları tercih ediniz. Size ARFID kısıtlamalarınıza uygun farklı ve güvenli bir tarif önermemi ister misiniz?`;
}

module.exports = {
    validateDietaryOutput,
    createSafetyFallbackResponse
};
