/**
 * Dietary Guardrail Module
 * Layer 3 Post-Generation Deterministic Safety Filter.
 * 
 * Inspects LLM output against user's personal avoid foods list.
 * Uses shared normalization from fuzzyMatch.js to handle Turkish suffixes (somon -> somonlu/somondan).
 */

const { normalizeString } = require("../tools/utils/fuzzyMatch");
const { calorieDatabase } = require("../tools/data/calorieDatabase");

// Fast alias map for bilingual food checks
const aliasLookup = new Map();
if (Array.isArray(calorieDatabase)) {
    calorieDatabase.forEach(entry => {
        const allTerms = [entry.name, ...(entry.aliases || [])].map(t => normalizeString(t)).filter(Boolean);
        allTerms.forEach(term => {
            if (!aliasLookup.has(term)) {
                aliasLookup.set(term, allTerms);
            }
        });
    });
}

/**
 * Validates assistant response text against user's avoid foods.
 * Supports intent disambiguation via options.isRecipeRecommendation:
 * - When isRecipeRecommendation === true (Hard Mode): Blocks response if avoid foods are mentioned.
 * - When isRecipeRecommendation === false (Soft Mode - Informational/Calories): Allows response and generates a deterministic warning notice.
 * 
 * @param {string} assistantText - Raw response text generated by LLM
 * @param {Array<string>} unsafeFoods - List of unsafe/avoid food names for the user
 * @param {{ isRecipeRecommendation?: boolean }} [options={}] - Validation options
 * @returns {{ isSafe: boolean, blockedFoods: Array<string>, warningNotice?: string }} Validation result
 */
function validateDietaryOutput(assistantText, unsafeFoods = [], options = {}) {
    if (!assistantText || typeof assistantText !== "string" || !Array.isArray(unsafeFoods) || unsafeFoods.length === 0) {
        return { isSafe: true, blockedFoods: [] };
    }

    const isRecipeRecommendation = options.isRecipeRecommendation !== undefined ? options.isRecipeRecommendation : true;
    const normalizedText = normalizeString(assistantText);
    const wordsInText = normalizedText.split(/\s+/);
    const detectedBreaches = new Set();

    for (const rawFood of unsafeFoods) {
        if (!rawFood || typeof rawFood !== "string") continue;
        const normalizedFood = normalizeString(rawFood);
        if (!normalizedFood || normalizedFood.length < 2) continue;

        const termsToSearch = aliasLookup.get(normalizedFood) || [normalizedFood];

        for (const term of termsToSearch) {
            if (!term || term.length < 2) continue;

            // 1. Çok kelimeli gıdalar (örn. "balik corbasi", "kirmizi et") için metin içinde substring kontrolü
            if (term.includes(" ")) {
                if (normalizedText.includes(term)) {
                    detectedBreaches.add(rawFood);
                    break;
                }
                continue;
            }

            // 2. Tek kelimeli gıdalar için Türkçe ekleri (somon -> somonlu, somondan, somonun)
            // kelime başlangıcı (startsWith) ve tam kelime eşleşmesiyle yakalama
            let termMatched = false;
            for (const word of wordsInText) {
                if (word.startsWith(term)) {
                    // Aşırı kısa köklerin yanlışlıkla uzun alakasız kelimelerle eşleşmesini önleme (örn. "et" -> "etkili")
                    if (term.length <= 2 && word !== term) {
                        continue;
                    }
                    detectedBreaches.add(rawFood);
                    termMatched = true;
                    break;
                }
            }
            if (termMatched) break;
        }
    }

    const blockedList = Array.from(detectedBreaches);

    // Soft Mode: If this is an informational query (not a recipe recommendation), don't hard-block
    if (!isRecipeRecommendation) {
        let notice = undefined;
        if (blockedList.length > 0) {
            notice = `\n\n💡 Not: Bu besin (${blockedList.join(", ")}) kişisel kaçındığınız gıdalar listenizde yer almaktadır. Bilgi amaçlı paylaşılmıştır.`;
        }
        return {
            isSafe: true,
            blockedFoods: blockedList,
            warningNotice: notice
        };
    }

    // Hard Mode: Recipe / Consumption recommendation with avoid foods
    return {
        isSafe: blockedList.length === 0,
        blockedFoods: blockedList
    };
}

/**
 * Generates an empathetic and safe generic fallback response when an unsafe food is caught.
 * 
 * @param {Array<string>} blockedFoods - Unsafe foods that triggered the guardrail
 * @returns {string} Safe fallback message
 */
function createSafetyFallbackResponse(blockedFoods = []) {
    const foodListText = blockedFoods.length > 0
        ? ` (${blockedFoods.join(", ")})`
        : "";

    return `Güvenlik Uyarısı: Önerim kişisel kaçındığınız gıdalar listenizde yer alan bir içerik${foodListText} barındırabileceğinden dolayı sağlığınızı korumak adına durdurulmuştur. Güvenli beslenme yolculuğunuz için lütfen listenizdeki tolere edebildiğiniz alternatif gıdaları tercih ediniz. Size ARFID kısıtlamalarınıza uygun farklı ve güvenli bir tarif önermemi ister misiniz?`;
}

module.exports = {
    validateDietaryOutput,
    createSafetyFallbackResponse
};
